language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "15"
before_script:
  - yarn lerna bootstrap
env:
  - PACKAGE=packages/local
  - PACKAGE=packages/gcs

cache: yarn
notifications:
  email: false
  webhooks: "https://ship.freshfox.at/travis/-1001141933878"

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      script:
        - echo "Running in package ${PACKAGE}"
        - cd ${PACKAGE}
        - yarn build
    - stage: test
      script:
        - echo "Running in package ${PACKAGE}"
        - cd ${PACKAGE}
        - yarn test

