name: like-fs CI

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: '/tmp/google-credentials-sa-node-${{ matrix.node }}-${{ matrix.package }}.json'
      STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
    strategy:
      matrix:
        package: [ local, gcs ]
        node: [ 12, 14, 16 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      # Initialize root cache
      - name: Cache dependencies
        uses: actions/cache@v2
        id: modules-cache
        with:
          path: 'packages/${{ matrix.package }}/node_modules'
          key: ${{ runner.os }}-node-modules-${{ matrix.package }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.modules-cache.outputs.cache-hit != 'true'
        run: yarn lerna bootstrap
      - name: Build package
        run: cd packages/${{ matrix.package }} && yarn build
      - name: Prepare tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
        run: |
          cd packages/${{ matrix.package }}
          npm run test:prepare --if-present
      - name: Test package
        run: |
          cd packages/${{ matrix.package }}
          yarn test
